//-----------------------------------------------------------------------------
// Copyright 2022, Ed Keenan, all rights reserved.
//-----------------------------------------------------------------------------  

#ifndef UNIT_TEST_CONFIGURATION_H
#define UNIT_TEST_CONFIGURATION_H

// Make sure all are enabled for final submission...
//      I grade whatever is set in this file - Keenan


#define Combo_Junkfood                          false                                   
#define Combo_VectCrossAddSub                   false                            
#define Combo_VectCrossAddSubMatrixMult         false                  
#define Combo_VectCrossAddSubMatrixMultCross    false             
#define Combo_VectCrossCrossNorm                false                         
#define Combo_VectLine                          false      

#define Mat3_Accessor_Get                       false                                
#define Mat3_Accessor_Get_Const                 false                          
#define Mat3_Accessor_Set                       false                                
#define Mat3_AddEqual_Mat3                      false                             
#define Mat3_Add_Mat3                           false                                  
#define Mat3_AssignmentOperator                 false                          
#define Mat3_Bracket_Get                        false                                 
#define Mat3_Bracket_Get_Const                  false                           
#define Mat3_Bracket_Set                        false                                 
#define Mat3_Copy_Constructor                   false                            
#define Mat3_Default_Constructor                false                         
#define Mat3_Destructor_Constuctor              false                       
#define Mat3_Det                                false  
#define Mat3_GetInverse                         false                                  
#define Mat3_GetTranspose                       false                                
#define Mat3_GET_ROW_0                          false                                   
#define Mat3_GET_ROW_1                          false                                   
#define Mat3_GET_ROW_2                          false                                                                    
#define Mat3_Inverse                            false                                     
#define Mat3_isEqual_false                      false                               
#define Mat3_MultEqual_Mat3                     false                              
#define Mat3_Mult_Mat3                          false                          
#define Mat3_Mult_Scale                         false                                
#define Mat3_Scale_Equals                       false                                
#define Mat3_Scale_Mat3                         false                                
#define Mat3_SET_Identity                       false                                                            
#define Mat3_SET_ROW_0                          false                                   
#define Mat3_SET_ROW_1                          false                                   
#define Mat3_SET_ROW_2                          false                                                                                                 
#define Mat3_SET_Vectors                        false                                 
#define Mat3_SET_Zero                           false
#define Mat3_Special_isEqual_false2             false                      
#define Mat3_Special_isEqual_true               false                        
#define Mat3_Special_isIdentity_false           false                    
#define Mat3_Special_isIdentity_true            false                     
#define Mat3_Special_Matrix_Identity            false                                       
#define Mat3_Special_Matrix_Zero                false                                                        
#define Mat3_SubEqual_Mat3                      false                             
#define Mat3_Sub_Mat3                           false                                  
#define Mat3_Transpose                          false                                                                      
#define Mat3_UnaryMinus                         false                                
#define Mat3_UnaryPlus                          false                                 
#define Mat3_Unary_equal_Minus                  false                         
#define Mat3_Unary_equal_Plus                   false   
#define Mat3_Vector_Constructor                 false   

#define Mat4_Accessor_Get                       false                                
#define Mat4_Accessor_Get_Const                 false                          
#define Mat4_Accessor_Set                       false                                
#define Mat4_AddEqual_Mat4                      false                             
#define Mat4_Add_Mat4                           false                                  
#define Mat4_AssignmentOperator                 false                          
#define Mat4_Bracket_Get                        false                                 
#define Mat4_Bracket_Get_Const                  false                           
#define Mat4_Bracket_Set                        false                                 
#define Mat4_Copy_Constructor                   false                            
#define Mat4_Default_Constructor                false                         
#define Mat4_Destructor_Constuctor              false                       
#define Mat4_Det                                false                                         
#define Mat4_GetInverse                         false                                  
#define Mat4_GetTranspose                       false                                
#define Mat4_GET_ROW_0                          false                                   
#define Mat4_GET_ROW_1                          false                                   
#define Mat4_GET_ROW_2                          false                                   
#define Mat4_GET_ROW_3                          false                                   
#define Mat4_Inverse                            false                                     
#define Mat4_isEqual_false                      false                                                           
#define Mat4_MultEqual_Mat4                     false                              
#define Mat4_Mult_Mat4                          false                          
#define Mat4_Mult_Scale                         false                                
#define Mat4_RotAxisAngle                       false                                
#define Mat4_RotInverseOrient                   false                            
#define Mat4_RotOrient                          false                                   
#define Mat4_Scale_Equals                       false                                
#define Mat4_Scale_Mat4                         false                                
#define Mat4_SET_Identity                       false                                
#define Mat4_SET_MatrixRotAxisAngle             false                      
#define Mat4_SET_MatrixRotInverseOrient         false                  
#define Mat4_SET_MatrixRotOrient                false                         
#define Mat4_SET_RotX                           false                                    
#define Mat4_SET_RotXYZ                         false                                  
#define Mat4_SET_RotY                           false                                    
#define Mat4_SET_RotZ                           false                                    
#define Mat4_SET_ROW_0                          false                                   
#define Mat4_SET_ROW_1                          false                                   
#define Mat4_SET_ROW_2                          false                                   
#define Mat4_SET_ROW_3                          false                                   
#define Mat4_SET_SCALE                          false                                   
#define Mat4_SET_SCALE_Vect                     false                              
#define Mat4_SET_Trans                          false                                   
#define Mat4_SET_Trans_Vect                     false                              
#define Mat4_SET_Vectors                        false                                 
#define Mat4_SET_Zero                           false                                    
#define Mat4_Special_isEqual_false2             false                      
#define Mat4_Special_isEqual_true               false                        
#define Mat4_Special_isIdentity_false           false                    
#define Mat4_Special_isIdentity_true            false                     
#define Mat4_Special_Matrix_Identity            false                     
#define Mat4_Special_Matrix_SCALE               false                        
#define Mat4_Special_Matrix_SCALE_Vect          false                   
#define Mat4_Special_Matrix_Trans               false                        
#define Mat4_Special_Matrix_Trans_Vect          false                   
#define Mat4_Special_Matrix_Zero                false                         
#define Mat4_Special_RotX                       false                                
#define Mat4_Special_RotXYZ_Constructor         false                  
#define Mat4_Special_RotY                       false                                
#define Mat4_Special_RotZ                       false                                
#define Mat4_SubEqual_Mat4                      false                             
#define Mat4_Sub_Mat4                           false                                  
#define Mat4_Transpose                          false                                   
#define Mat4_UnaryMinus                         false                                
#define Mat4_UnaryPlus                          false                                 
#define Mat4_Unary_equal_Minus                  false                         
#define Mat4_Unary_equal_Plus                   false   
#define Mat4_Vector_Constructor                 false    

#define SpeedTestA                              false                                       
#define SpeedTestB                              false                                       
#define SpeedTestC                              false                                       
#define SpeedTestD                              false                                       
#define SpeedTestE                              false                                       
#define SpeedTestF                              false                                       
#define SpeedTestG                              false                                       
#define SpeedTestH                              false     
									            
#define Trig_ACos                               false                                        
#define Trig_ASin                               false                                        
#define Trig_ATan                               false                                        
#define Trig_ATan2                              false                                       
#define Trig_Cos                                false                                         
#define Trig_CosSin                             false                                      
#define Trig_InvSqrt                            false                                     
#define Trig_Sin                                false                                         
#define Trig_Sqrt                               false                                        
#define Trig_Tan                                false    

#define Vec3_Add_Vec3                           false                                    
#define Vec3_Assignment_Operator                false                         
#define Vec3_ConstantCheck                      false                               
#define Vec3_Constructor_Copy                   false                            
#define Vec3_Constructor_Default                false                         
#define Vec3_Constructor_Individual             false                       
#define Vec3_Constructor_Vec4                   false                             
#define Vec3_Cross                              false                                       
#define Vec3_Destructor                         false                                  
#define Vec3_Dot                                false                                         
#define Vec3_Get_Accessors                      false                               
#define Vec3_Get_Accessors_const                false                         
#define Vec3_Get_Angle                          false                                   
#define Vec3_Get_Brackets                       false                                
#define Vec3_Get_Brackets_const                 false                          
#define Vec3_Get_Normalize                      false                               
#define Vec3_IsEqualFalse                       false                                
#define Vec3_IsEqualFalse_default               false                        
#define Vec3_IsEqualTrue                        false                                 
#define Vec3_IsEqualTrue_default                false                         
#define Vec3_IsZeroFalse                        false                                 
#define Vec3_IsZeroFalse_default                false                         
#define Vec3_IsZeroTrue_default                 false                          
#define Vec3_IsZeroTrue_True                    false                             
#define Vec3_Len                                false                                         
#define Vec3_MultEqual_Mat3                     false                              
#define Vec3_MultEqual_Mat4                     false                              
#define Vec3_Mult_Mat3                          false                                   
#define Vec3_Mult_Mat4                          false                                   
#define Vec3_Mult_Scale                         false                                  
#define Vec3_Normalize                          false                                   
#define Vec3_PlusEqual_Vect                     false                              
#define Vec3_Proxy                              false                                       
#define Vec3_SampleTest                         false                                  
#define Vec3_ScaleEquals                        false                                 
#define Vec3_Scale_Vect                         false                                  
#define Vec3_Set_3_Elements                     false                              
#define Vec3_Set_Accessors                      false                               
#define Vec3_Set_Accessors_get                  false                           
#define Vec3_Set_Brackets                       false                                
#define Vec3_Set_Brackets_get                   false                            
#define Vec3_Set_Vec3                           false                                    
#define Vec3_Set_Vec4                           false                                    
#define Vec3_SubEqual_Vect                      false                               
#define Vec3_Sub_Vect                           false                                    
#define Vec3_Unary_equal_Minus                  false                           
#define Vec3_Unary_equal_Plus                   false                            
#define Vec3_Unary_Minus                        false                                 
#define Vec3_Unary_Plus                         false    
									            
#define Vec4_Add_Vec4                           false                                    
#define Vec4_Assignment_Operator                false                         
#define Vec4_ConstantCheck                      false                               
#define Vec4_Constructor_Copy                   false  
#define Vec4_Constructor_Default                false                            
#define Vec4_Constructor_Individual             false                      
#define Vec4_Constructor_Vec3                   false
#define Vec4_Destructor                         false                                  
#define Vec4_Dot                                false                                         
#define Vec4_Get_Accessors                      false                               
#define Vec4_Get_Accessors_const                false                         
#define Vec4_Get_Brackets                       false                                
#define Vec4_Get_Brackets_const                 false                          
#define Vec4_Get_Normalize                      false                               
#define Vec4_IsEqualFalse                       false                                
#define Vec4_IsEqualFalse_default               false                        
#define Vec4_IsEqualTrue                        false                                 
#define Vec4_IsEqualTrue_default                false                         
#define Vec4_IsZeroFalse                        false                                 
#define Vec4_IsZeroFalse_default                false                         
#define Vec4_IsZeroTrue_default                 false                          
#define Vec4_IsZeroTrue_True                    false                             
#define Vec4_Len                                false                                         
#define Vec4_MultEqual_Mat4                     false                              
#define Vec4_Mult_Mat4                          false                                   
#define Vec4_Mult_Scale                         false                                  
#define Vec4_Normalize                          false                                   
#define Vec4_PlusEqual_Vec4                     false                              
#define Vec4_Proxy                              false                                       
#define Vec4_SampleTest                         false                                  
#define Vec4_ScaleEquals                        false                                 
#define Vec4_Scale_Vec4                         false                                  
#define Vec4_Set_4_Elements                     false                              
#define Vec4_Set_Accessors                      false                               
#define Vec4_Set_Accessors_Get                  false                           
#define Vec4_Set_Brackets                       false                                
#define Vec4_Set_Brackets_get                   false                            
#define Vec4_Set_Vec3                           false                                    
#define Vec4_Set_Vec4                           false                                    
#define Vec4_SubEqual_Vec4                      false                               
#define Vec4_Sub_Vec4                           false                                    
#define Vec4_Unary_equal_Minus                  false                           
#define Vec4_Unary_equal_Plus                   false                            
#define Vec4_Unary_Minus                        false                                 
#define Vec4_Unary_Plus                         false                                  

		       
#endif

// ---  End of File ---------------
