// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Matrix_Composition.proto

#include "Matrix_Composition.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR Matrix_Composition_proto::Matrix_Composition_proto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.v0_)*/nullptr
  , /*decltype(_impl_.v1_)*/nullptr
  , /*decltype(_impl_.v2_)*/nullptr
  , /*decltype(_impl_.v3_)*/nullptr} {}
struct Matrix_Composition_protoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Matrix_Composition_protoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Matrix_Composition_protoDefaultTypeInternal() {}
  union {
    Matrix_Composition_proto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Matrix_Composition_protoDefaultTypeInternal _Matrix_Composition_proto_default_instance_;

// ===================================================================

class Matrix_Composition_proto::_Internal {
 public:
  using HasBits = decltype(std::declval<Matrix_Composition_proto>()._impl_._has_bits_);
  static const ::Vect_proto& v0(const Matrix_Composition_proto* msg);
  static void set_has_v0(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::Vect_proto& v1(const Matrix_Composition_proto* msg);
  static void set_has_v1(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static const ::Vect_proto& v2(const Matrix_Composition_proto* msg);
  static void set_has_v2(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static const ::Vect_proto& v3(const Matrix_Composition_proto* msg);
  static void set_has_v3(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
};

const ::Vect_proto&
Matrix_Composition_proto::_Internal::v0(const Matrix_Composition_proto* msg) {
  return *msg->_impl_.v0_;
}
const ::Vect_proto&
Matrix_Composition_proto::_Internal::v1(const Matrix_Composition_proto* msg) {
  return *msg->_impl_.v1_;
}
const ::Vect_proto&
Matrix_Composition_proto::_Internal::v2(const Matrix_Composition_proto* msg) {
  return *msg->_impl_.v2_;
}
const ::Vect_proto&
Matrix_Composition_proto::_Internal::v3(const Matrix_Composition_proto* msg) {
  return *msg->_impl_.v3_;
}
void Matrix_Composition_proto::clear_v0() {
  if (_impl_.v0_ != nullptr) _impl_.v0_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void Matrix_Composition_proto::clear_v1() {
  if (_impl_.v1_ != nullptr) _impl_.v1_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
void Matrix_Composition_proto::clear_v2() {
  if (_impl_.v2_ != nullptr) _impl_.v2_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
void Matrix_Composition_proto::clear_v3() {
  if (_impl_.v3_ != nullptr) _impl_.v3_->Clear();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
Matrix_Composition_proto::Matrix_Composition_proto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Matrix_Composition_proto)
}
Matrix_Composition_proto::Matrix_Composition_proto(const Matrix_Composition_proto& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  Matrix_Composition_proto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.v0_){nullptr}
    , decltype(_impl_.v1_){nullptr}
    , decltype(_impl_.v2_){nullptr}
    , decltype(_impl_.v3_){nullptr}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  if (from._internal_has_v0()) {
    _this->_impl_.v0_ = new ::Vect_proto(*from._impl_.v0_);
  }
  if (from._internal_has_v1()) {
    _this->_impl_.v1_ = new ::Vect_proto(*from._impl_.v1_);
  }
  if (from._internal_has_v2()) {
    _this->_impl_.v2_ = new ::Vect_proto(*from._impl_.v2_);
  }
  if (from._internal_has_v3()) {
    _this->_impl_.v3_ = new ::Vect_proto(*from._impl_.v3_);
  }
  // @@protoc_insertion_point(copy_constructor:Matrix_Composition_proto)
}

inline void Matrix_Composition_proto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.v0_){nullptr}
    , decltype(_impl_.v1_){nullptr}
    , decltype(_impl_.v2_){nullptr}
    , decltype(_impl_.v3_){nullptr}
  };
}

Matrix_Composition_proto::~Matrix_Composition_proto() {
  // @@protoc_insertion_point(destructor:Matrix_Composition_proto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Matrix_Composition_proto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.v0_;
  if (this != internal_default_instance()) delete _impl_.v1_;
  if (this != internal_default_instance()) delete _impl_.v2_;
  if (this != internal_default_instance()) delete _impl_.v3_;
}

void Matrix_Composition_proto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Matrix_Composition_proto::Clear() {
// @@protoc_insertion_point(message_clear_start:Matrix_Composition_proto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(_impl_.v0_ != nullptr);
      _impl_.v0_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(_impl_.v1_ != nullptr);
      _impl_.v1_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(_impl_.v2_ != nullptr);
      _impl_.v2_->Clear();
    }
    if (cached_has_bits & 0x00000008u) {
      GOOGLE_DCHECK(_impl_.v3_ != nullptr);
      _impl_.v3_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* Matrix_Composition_proto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional .Vect_proto v0 = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_v0(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .Vect_proto v1 = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_v1(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .Vect_proto v2 = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_v2(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .Vect_proto v3 = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_v3(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Matrix_Composition_proto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Matrix_Composition_proto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // optional .Vect_proto v0 = 1;
  if (_internal_has_v0()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::v0(this),
        _Internal::v0(this).GetCachedSize(), target, stream);
  }

  // optional .Vect_proto v1 = 2;
  if (_internal_has_v1()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::v1(this),
        _Internal::v1(this).GetCachedSize(), target, stream);
  }

  // optional .Vect_proto v2 = 3;
  if (_internal_has_v2()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::v2(this),
        _Internal::v2(this).GetCachedSize(), target, stream);
  }

  // optional .Vect_proto v3 = 4;
  if (_internal_has_v3()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::v3(this),
        _Internal::v3(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Matrix_Composition_proto)
  return target;
}

size_t Matrix_Composition_proto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Matrix_Composition_proto)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // optional .Vect_proto v0 = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.v0_);
    }

    // optional .Vect_proto v1 = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.v1_);
    }

    // optional .Vect_proto v2 = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.v2_);
    }

    // optional .Vect_proto v3 = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.v3_);
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Matrix_Composition_proto::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const Matrix_Composition_proto*>(
      &from));
}

void Matrix_Composition_proto::MergeFrom(const Matrix_Composition_proto& from) {
  Matrix_Composition_proto* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:Matrix_Composition_proto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_mutable_v0()->::Vect_proto::MergeFrom(
          from._internal_v0());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_mutable_v1()->::Vect_proto::MergeFrom(
          from._internal_v1());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_mutable_v2()->::Vect_proto::MergeFrom(
          from._internal_v2());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_internal_mutable_v3()->::Vect_proto::MergeFrom(
          from._internal_v3());
    }
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void Matrix_Composition_proto::CopyFrom(const Matrix_Composition_proto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Matrix_Composition_proto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Matrix_Composition_proto::IsInitialized() const {
  return true;
}

void Matrix_Composition_proto::InternalSwap(Matrix_Composition_proto* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Matrix_Composition_proto, _impl_.v3_)
      + sizeof(Matrix_Composition_proto::_impl_.v3_)
      - PROTOBUF_FIELD_OFFSET(Matrix_Composition_proto, _impl_.v0_)>(
          reinterpret_cast<char*>(&_impl_.v0_),
          reinterpret_cast<char*>(&other->_impl_.v0_));
}

std::string Matrix_Composition_proto::GetTypeName() const {
  return "Matrix_Composition_proto";
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Matrix_Composition_proto*
Arena::CreateMaybeMessage< ::Matrix_Composition_proto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Matrix_Composition_proto >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
