// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Texture.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Texture_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Texture_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Texture_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Texture_2eproto {
  static const uint32_t offsets[];
};
class Texture_proto;
struct Texture_protoDefaultTypeInternal;
extern Texture_protoDefaultTypeInternal _Texture_proto_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Texture_proto* Arena::CreateMaybeMessage<::Texture_proto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class Texture_proto final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:Texture_proto) */ {
 public:
  inline Texture_proto() : Texture_proto(nullptr) {}
  ~Texture_proto() override;
  explicit PROTOBUF_CONSTEXPR Texture_proto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Texture_proto(const Texture_proto& from);
  Texture_proto(Texture_proto&& from) noexcept
    : Texture_proto() {
    *this = ::std::move(from);
  }

  inline Texture_proto& operator=(const Texture_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline Texture_proto& operator=(Texture_proto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Texture_proto& default_instance() {
    return *internal_default_instance();
  }
  static inline const Texture_proto* internal_default_instance() {
    return reinterpret_cast<const Texture_proto*>(
               &_Texture_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Texture_proto& a, Texture_proto& b) {
    a.Swap(&b);
  }
  inline void Swap(Texture_proto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Texture_proto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Texture_proto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Texture_proto>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Texture_proto& from);
  void MergeFrom(const Texture_proto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Texture_proto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Texture_proto";
  }
  protected:
  explicit Texture_proto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPoDataFieldNumber = 1,
    kDataSizeFieldNumber = 2,
  };
  // optional bytes poData = 1;
  bool has_podata() const;
  private:
  bool _internal_has_podata() const;
  public:
  void clear_podata();
  const std::string& podata() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_podata(ArgT0&& arg0, ArgT... args);
  std::string* mutable_podata();
  PROTOBUF_NODISCARD std::string* release_podata();
  void set_allocated_podata(std::string* podata);
  private:
  const std::string& _internal_podata() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_podata(const std::string& value);
  std::string* _internal_mutable_podata();
  public:

  // optional uint32 dataSize = 2;
  bool has_datasize() const;
  private:
  bool _internal_has_datasize() const;
  public:
  void clear_datasize();
  uint32_t datasize() const;
  void set_datasize(uint32_t value);
  private:
  uint32_t _internal_datasize() const;
  void _internal_set_datasize(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Texture_proto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr podata_;
    uint32_t datasize_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Texture_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Texture_proto

// optional bytes poData = 1;
inline bool Texture_proto::_internal_has_podata() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Texture_proto::has_podata() const {
  return _internal_has_podata();
}
inline void Texture_proto::clear_podata() {
  _impl_.podata_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Texture_proto::podata() const {
  // @@protoc_insertion_point(field_get:Texture_proto.poData)
  return _internal_podata();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Texture_proto::set_podata(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.podata_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Texture_proto.poData)
}
inline std::string* Texture_proto::mutable_podata() {
  std::string* _s = _internal_mutable_podata();
  // @@protoc_insertion_point(field_mutable:Texture_proto.poData)
  return _s;
}
inline const std::string& Texture_proto::_internal_podata() const {
  return _impl_.podata_.Get();
}
inline void Texture_proto::_internal_set_podata(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.podata_.Set(value, GetArenaForAllocation());
}
inline std::string* Texture_proto::_internal_mutable_podata() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.podata_.Mutable(GetArenaForAllocation());
}
inline std::string* Texture_proto::release_podata() {
  // @@protoc_insertion_point(field_release:Texture_proto.poData)
  if (!_internal_has_podata()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.podata_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.podata_.IsDefault()) {
    _impl_.podata_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Texture_proto::set_allocated_podata(std::string* podata) {
  if (podata != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.podata_.SetAllocated(podata, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.podata_.IsDefault()) {
    _impl_.podata_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Texture_proto.poData)
}

// optional uint32 dataSize = 2;
inline bool Texture_proto::_internal_has_datasize() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Texture_proto::has_datasize() const {
  return _internal_has_datasize();
}
inline void Texture_proto::clear_datasize() {
  _impl_.datasize_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline uint32_t Texture_proto::_internal_datasize() const {
  return _impl_.datasize_;
}
inline uint32_t Texture_proto::datasize() const {
  // @@protoc_insertion_point(field_get:Texture_proto.dataSize)
  return _internal_datasize();
}
inline void Texture_proto::_internal_set_datasize(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.datasize_ = value;
}
inline void Texture_proto::set_datasize(uint32_t value) {
  _internal_set_datasize(value);
  // @@protoc_insertion_point(field_set:Texture_proto.dataSize)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Texture_2eproto
