// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: testData.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_testData_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_testData_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_testData_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_testData_2eproto {
  static const uint32_t offsets[];
};
class testData_proto;
struct testData_protoDefaultTypeInternal;
extern testData_protoDefaultTypeInternal _testData_proto_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::testData_proto* Arena::CreateMaybeMessage<::testData_proto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class testData_proto final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:testData_proto) */ {
 public:
  inline testData_proto() : testData_proto(nullptr) {}
  ~testData_proto() override;
  explicit PROTOBUF_CONSTEXPR testData_proto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  testData_proto(const testData_proto& from);
  testData_proto(testData_proto&& from) noexcept
    : testData_proto() {
    *this = ::std::move(from);
  }

  inline testData_proto& operator=(const testData_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline testData_proto& operator=(testData_proto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const testData_proto& default_instance() {
    return *internal_default_instance();
  }
  static inline const testData_proto* internal_default_instance() {
    return reinterpret_cast<const testData_proto*>(
               &_testData_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(testData_proto& a, testData_proto& b) {
    a.Swap(&b);
  }
  inline void Swap(testData_proto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(testData_proto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  testData_proto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<testData_proto>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const testData_proto& from);
  void MergeFrom(const testData_proto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(testData_proto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "testData_proto";
  }
  protected:
  explicit testData_proto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXValFieldNumber = 1,
  };
  // optional uint32 x_val = 1;
  bool has_x_val() const;
  private:
  bool _internal_has_x_val() const;
  public:
  void clear_x_val();
  uint32_t x_val() const;
  void set_x_val(uint32_t value);
  private:
  uint32_t _internal_x_val() const;
  void _internal_set_x_val(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:testData_proto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t x_val_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_testData_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// testData_proto

// optional uint32 x_val = 1;
inline bool testData_proto::_internal_has_x_val() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool testData_proto::has_x_val() const {
  return _internal_has_x_val();
}
inline void testData_proto::clear_x_val() {
  _impl_.x_val_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline uint32_t testData_proto::_internal_x_val() const {
  return _impl_.x_val_;
}
inline uint32_t testData_proto::x_val() const {
  // @@protoc_insertion_point(field_get:testData_proto.x_val)
  return _internal_x_val();
}
inline void testData_proto::_internal_set_x_val(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.x_val_ = value;
}
inline void testData_proto::set_x_val(uint32_t value) {
  _internal_set_x_val(value);
  // @@protoc_insertion_point(field_set:testData_proto.x_val)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_testData_2eproto
